spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
  jpa:
    show-sql: true
    database: MySQL
    hibernate:
      ddl-auto: update