INSERT INTO APP_USER(USERNAME, PASSWORD) VALUES('kelvin','ZH798F987');
INSERT INTO APP_USER(USERNAME, PASSWORD) VALUES('jack','$2a$10$hj6S9qG7MiH7OhPxqaEXWuE.s8oN8BTAWHOVKe5SATDwNr7Z8OCH.');

INSERT INTO APP_ROLE(APP_USER_ID, APP_ROLE) VALUES(1,'ADMIN');
INSERT INTO APP_ROLE(APP_USER_ID, APP_ROLE) VALUES(1,'MEMBER');

INSERT INTO APP_ROLE(APP_USER_ID, APP_ROLE) VALUES(2,'ADMIN');
INSERT INTO APP_ROLE(APP_USER_ID, APP_ROLE) VALUES(2,'MEMBER');